# Numpy

Numpy is a commonly used python library that allows for the very efficient (fast) processing on arrays (and matrices -- which are arrays, but often don't get viewed as such)

## One dimensional array from a list

In [1]:
import numpy as np

In [2]:
alist = [1,2,3,4]
ra1 = np.array(alist)
ra1


array([1, 2, 3, 4])

In [3]:
ra2 = np.array([5,6,7,8])
ra2

array([5, 6, 7, 8])

## Multi-dimensional arrays

In [4]:
ra3 = np.array([[9,10,11,12], [13,14,15,16]])
ra3

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
ra1.shape

(4,)

In [6]:
ra3.shape

(2, 4)

## Linear (matrix) algebra

In [7]:
ra4 = np.arange(0,10,2)
ra4

array([0, 2, 4, 6, 8])

In [8]:
ra5 = np.linspace(0,10,6)
ra5

array([  0.,   2.,   4.,   6.,   8.,  10.])

In [9]:
ra5.resize(3,2)
ra5

array([[  0.,   2.],
       [  4.,   6.],
       [  8.,  10.]])

In [10]:
ra5.resize(2,3)
ra5

array([[  0.,   2.,   4.],
       [  6.,   8.,  10.]])

In [11]:
np.zeros((3,3))


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [13]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.diag(np.linspace(0,10,6))

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   2.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   4.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   6.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   8.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  10.]])

In [15]:
np.array([1,2,3]*4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [17]:
x = np.ones((3,2))
x

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [18]:
x*x

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [19]:
2*x

array([[ 2.,  2.],
       [ 2.,  2.],
       [ 2.,  2.]])

In [20]:
y = np.array([1,2,4])
y.resize(3,1)
y

array([[1],
       [2],
       [4]])

In [21]:
x*y

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 4.,  4.]])

In [22]:
x+2

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [23]:
z = (x*y+3)/2
z

array([[ 2. ,  2. ],
       [ 2.5,  2.5],
       [ 3.5,  3.5]])

In [24]:
np.vstack([x+2,z/3])

array([[ 3.        ,  3.        ],
       [ 3.        ,  3.        ],
       [ 3.        ,  3.        ],
       [ 0.66666667,  0.66666667],
       [ 0.83333333,  0.83333333],
       [ 1.16666667,  1.16666667]])

In [25]:
np.hstack([x+2,z/3])

array([[ 3.        ,  3.        ,  0.66666667,  0.66666667],
       [ 3.        ,  3.        ,  0.83333333,  0.83333333],
       [ 3.        ,  3.        ,  1.16666667,  1.16666667]])

In [26]:
x

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [27]:
x*2

array([[ 2.,  2.],
       [ 2.,  2.],
       [ 2.,  2.]])

In [28]:
x.resize(2,3)
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [29]:
x.reshape(3,2) # note that reshape returns a reshapen matrix, but keeps the original array dimensions in tact

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [30]:
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [32]:
x.T # transpose

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [33]:
x = np.linspace(0,10,9)
x.reshape(3,3)


array([[  0.  ,   1.25,   2.5 ],
       [  3.75,   5.  ,   6.25],
       [  7.5 ,   8.75,  10.  ]])

In [34]:
x.max()

10.0

In [35]:
x.min()

0.0

In [36]:
x.mean() # mean (aka average) of all values in the array

5.0

In [37]:
x.std() # standard deviation of all values in the array

3.2274861218395139

In [38]:
x.argmax() # index (zero based) to maximum value found in array

8

In [39]:
x.argmin() # index (zero based) to minimum value found in array

0

# Slicing arrays

In [40]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
x[0]

0

In [42]:
x[87]

87

In [43]:
x[1:3]

array([1, 2])

In [44]:
x[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[1:10:2]

array([1, 3, 5, 7, 9])

In [46]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [47]:
x[::2]=-1
x

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1,
       17, -1, 19, -1, 21, -1, 23, -1, 25, -1, 27, -1, 29, -1, 31, -1, 33,
       -1, 35, -1, 37, -1, 39, -1, 41, -1, 43, -1, 45, -1, 47, -1, 49, -1,
       51, -1, 53, -1, 55, -1, 57, -1, 59, -1, 61, -1, 63, -1, 65, -1, 67,
       -1, 69, -1, 71, -1, 73, -1, 75, -1, 77, -1, 79, -1, 81, -1, 83, -1,
       85, -1, 87, -1, 89, -1, 91, -1, 93, -1, 95, -1, 97, -1, 99])

In [48]:
x = np.arange(100)
x.resize(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
x[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [50]:
x[1:2,0]

array([10])

In [51]:
x[1:2,:3]

array([[10, 11, 12]])

In [52]:
x[1:2,4:6]

array([[14, 15]])

In [53]:
x>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [54]:
x[x>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## This is where it get's weird (well, not really -- just remember that array vars are references)

In [55]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
y=x[3:7,3:7]
y

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [57]:
y[:]=0
y

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32,  0,  0,  0,  0, 37, 38, 39],
       [40, 41, 42,  0,  0,  0,  0, 47, 48, 49],
       [50, 51, 52,  0,  0,  0,  0, 57, 58, 59],
       [60, 61, 62,  0,  0,  0,  0, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
x = np.arange(100)
x.resize(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [60]:
y = x.copy()[3:7,3:7]
y

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [61]:
y[:]=0
y

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
x  # now, notice that we have not altered our original array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Boolean arrays

In [63]:
z=np.repeat(True,100)
z.resize(10,10)
z

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [64]:
z[3:7,3:7]=False
z

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [65]:
x[z]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 37,
       38, 39, 40, 41, 42, 47, 48, 49, 50, 51, 52, 57, 58, 59, 60, 61, 62,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Drawing from distributions

### Uniform distributions

In [67]:
np.random.random_sample(100)

array([ 0.61713258,  0.60856438,  0.69028653,  0.75227321,  0.92015391,
        0.58605359,  0.47874358,  0.65027073,  0.81114855,  0.96914127,
        0.94836487,  0.81586023,  0.27607061,  0.57570179,  0.05556483,
        0.69764944,  0.21515019,  0.51045379,  0.36897676,  0.90230679,
        0.1455502 ,  0.93863508,  0.49035387,  0.06220054,  0.88884769,
        0.51390958,  0.25716753,  0.32551381,  0.20786876,  0.24955957,
        0.00664486,  0.21812425,  0.85614549,  0.44362814,  0.23039301,
        0.5952046 ,  0.67384621,  0.18917303,  0.7963599 ,  0.92460818,
        0.76871747,  0.11759111,  0.42984421,  0.27628732,  0.17388075,
        0.10266094,  0.77052263,  0.05244381,  0.00438116,  0.01684067,
        0.53576015,  0.16729094,  0.50764152,  0.18396648,  0.61354705,
        0.67867764,  0.64551886,  0.49364249,  0.06277068,  0.64088162,
        0.64781842,  0.31328648,  0.43370371,  0.42590605,  0.41506479,
        0.64436532,  0.22980452,  0.7484474 ,  0.58017553,  0.81

In [71]:
np.random.random_sample((5,5))

array([[ 0.70547051,  0.87136436,  0.68359388,  0.58265803,  0.85883486],
       [ 0.44872225,  0.91119766,  0.96242425,  0.94283752,  0.28771435],
       [ 0.94799985,  0.03914373,  0.19467827,  0.00593229,  0.01083657],
       [ 0.35984383,  0.774179  ,  0.88000803,  0.33457593,  0.31137568],
       [ 0.17892682,  0.9977029 ,  0.03336423,  0.47754404,  0.86890461]])

In [75]:
np.random.random_sample((5,5))*10

array([[ 1.67773154,  1.51855028,  4.10046203,  3.22569953,  1.06906356],
       [ 0.76284912,  0.98047001,  2.38655085,  2.57894265,  9.81626063],
       [ 5.15544619,  2.5275857 ,  9.9713088 ,  1.3153633 ,  7.67692647],
       [ 6.01189638,  8.52711505,  5.90752198,  6.38097563,  6.59917691],
       [ 8.91192894,  1.46953844,  4.79585985,  2.77866357,  2.76470787]])

In [78]:
np.random.randint(10,size=10)

array([0, 9, 2, 7, 2, 1, 6, 5, 4, 4])

In [80]:
np.random.randint(10,size=(5,5))

array([[0, 8, 9, 8, 8],
       [0, 8, 4, 7, 9],
       [5, 8, 8, 5, 4],
       [2, 5, 6, 8, 7],
       [6, 1, 7, 4, 3]])

### Normal (gaussian) distribution

In [85]:
np.random.randn(5,5)

array([[ 0.28523906, -0.41756854,  1.62850813,  0.8072282 ,  1.51887818],
       [ 1.47221858,  0.86835716, -0.64610648,  1.42756289,  1.1781675 ],
       [ 1.40371064,  0.15767823, -1.22001311, -1.82524209,  1.15589515],
       [-1.65679669,  0.26979825,  0.35896567, -0.08277297, -1.13797586],
       [-0.35525898,  1.03582372,  0.20843302,  1.35880224,  0.74497473]])

In [86]:
x=100*np.random.randn(5,5)
x

array([[-129.75997108,  208.90780375,  -98.65340094,  -17.40144688,
         -40.52881433],
       [ -66.34989105,  217.36757925,  127.188328  ,    6.64954384,
         325.95710102],
       [ -63.48058567,   59.28271078,  -22.35681803,   91.93977471,
         -30.06290233],
       [-170.38746248,   78.85951234,  -13.98571553,  -54.77259073,
          -2.40915472],
       [ 224.22017586,  -56.05687677,  155.64423438,  103.88096201,
          24.5562287 ]])

In [90]:
x = np.trunc(x)
x

array([[-129.,  208.,  -98.,  -17.,  -40.],
       [ -66.,  217.,  127.,    6.,  325.],
       [ -63.,   59.,  -22.,   91.,  -30.],
       [-170.,   78.,  -13.,  -54.,   -2.],
       [ 224.,  -56.,  155.,  103.,   24.]])

In [ ]:
### ... Etc. (poisson, )